name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SystemVerilog Linter
      uses: dalance/svlint-action@v1
      with:
        files: |
          *.sv

