name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: locate
      run:  echo "$(realpath .)"
      
    - name: list
      run:  find -name "*" >> log.txt
      
    - name: print
      run:  cat log.txt
